# Generated by Django 4.0 on 2024-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_Image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
