# Generated by Django 4.0 on 2024-04-17 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='Availability_Status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='Is_Visible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('Image_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_Image', models.ImageField(upload_to='property_images/')),
                ('Property_Listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.propertylisting')),
            ],
        ),
    ]
