# Generated by Django 4.0 on 2024-04-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_propertylisting_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('Neighborhood_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Neighborhood_Name', models.CharField(max_length=200)),
            ],
        ),
    ]
