# Generated by Django 4.0 on 2024-04-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='Listing_Neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.neighborhood'),
        ),
    ]
