# Generated by Django 4.0 on 2024-04-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_propertylisting_listing_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Type',
            fields=[
                ('Home_Type_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Type_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
