# Generated by Django 4.0 on 2024-04-19 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_home_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='Listing_Home_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realestate.home_type'),
        ),
    ]
