# Generated by Django 4.0 on 2024-04-30 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_propertylisting_listing_home_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='Property_Listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realestate.propertylisting'),
        ),
    ]
