# Generated by Django 4.0 on 2024-05-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realestate', '0008_pricerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propery_Search_Log',
            fields=[
                ('Search_Log_Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitor_Search_Date', models.DateField(blank=True, null=True)),
                ('Home_Type_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realestate.home_type')),
                ('Neighborhood_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realestate.neighborhood')),
                ('Price_Range_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realestate.pricerange')),
            ],
        ),
    ]
